### ISSUE TITLE
Multiple Shops

### ISSUE THREAD

**Issue by junaid33** [DimensionSoftware/generator-shopify-nextjs#1]
Hey! I'm also working on making a Next.js app using the Shopify Admin API. I wanted to make a personal dashboard that can handle multiple Shopify shops so you can see all your orders in 1 place. All the examples I have found work for 1 shop. Any insight on this?

**Comment by junaid33** [comment]
Also, can you provide an sample env file?

**Comment by beppu** [comment]
This generator is for Shopify apps that can potentially be sold in the [Shopify App Store](https://apps.shopify.com/).  Each installation of this kind of app is supposed to work on one store at a time.  If you're looking to build a web app (not a Shopify app) that has access to the Shopify Admin API of multiple stores, this is not the project you're looking for.

**Comment by junaid33** [comment]
Yes I see it is for a single apps, but I can tweak the app to support multiple shops since you are using Prisma to save the access tokens and shop names. The part I am stuck on is how to use koa-shopify-graphql-proxy to access multiple shops. If you are available for freelancing and can help with this problem, please let me know.

**Comment by beppu** [comment]
You wouldn't use koa-shopify-graphql-proxy to access multiple shops.  It just makes the [/admin/api/graphql.json](https://github.com/Shopify/quilt/blob/master/packages/koa-shopify-graphql-proxy/src/shopify-graphql-proxy.ts#L5) endpoint for the [Shopify Admin API](https://help.shopify.com/en/api/graphql-admin-api/getting-started#the-graphql-endpoint) more easily accessible to the client-side code of embedded Shopify apps by proxying https://your-shop.myshopify.com/admin/api/graphql.json to https://yourapp.com/graphql and handling the access token on the server-side.  That lets client-side code not have to know the access token to access the GraphQL Admin API.

With that said, if you had multiple access tokens for multiple stores available to you, you could just query them individually.  Let's say you're using [Apollo Client](https://www.apollographql.com/docs/react/essentials/get-started.html).  You could instantiate a separate client for each store you want to query.

**Comment by junaid33** [comment]
Yes this is exactly what I did before but the link on ApolloClient is throwing an error. Then I thought Shopify requires a proxy to access GraphQL on the Admin API. I have taken the app from the generator and tried to add the products from a Shopify store: https://github.com/junaid33/shopify-next/blob/master/components/ProductList.js. You can add the {SHOPNAME} and {SHOPTOKEN}. Thank you for all your help.

**Comment by junaid33** [comment]
Ok so it turns out you can't access the Admin API client side due to a CORS restriction by Shopify. That's why we have to proxy the graphQL server side. Can I possibly proxy multiple shops on different URLs? And use ApolloClient and choose the URI to hit? If so, how?

**Comment by khoerling** [comment]
You likely only need to configure ApolloClient based on the site's id/token and proxy through the same URL.
