### ISSUE TITLE
Yeoman error

### ISSUE THREAD

**Issue by bianchimro** [DimensionSoftware/generator-shopify-nextjs#2]
Hi and thanks for sharing this generator.
I got an issue when trying to generate my app:

```
AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /Users/bianchimro/.nvm/versions/node/v10.12.0/lib/node_modules/generator-shopify-nextjs/generators/app/templates/.gitignore
```

I fixed it locally by manually creating the .gitignore file in my global node_modules.
I think it's an issue with npm packaging

**Comment by beppu** [comment]
Thank you for the bug report.  I had never installed this via npm until now, so I had no idea this was broken the whole time.  I was just using the locally `npm link`ed version up until now where the `.gitignore` file *does* exist.  

This yeoman behavior caught me by total surprise:  https://github.com/yeoman/generator/issues/812

A fixed version should be published very soon.

**Comment by beppu** [comment]
Please give it another try:  https://www.npmjs.com/package/generator-shopify-nextjs

**Comment by bianchimro** [comment]
@beppu thanks for fixing it so quickly!
