### ISSUE TITLE
client not found in router '/shopify/uninstall'

### ISSUE THREAD

**Issue by duythien0912** [DimensionSoftware/generator-shopify-nextjs#4]
![image](https://user-images.githubusercontent.com/20185622/50330142-be3ed700-052c-11e9-89fd-6ae89354e991.png)

I think it should be

![image](https://user-images.githubusercontent.com/20185622/50330132-b5e69c00-052c-11e9-9c00-087672391ea4.png)

**Comment by beppu** [comment]
Thanks for the bug report.
